name: Docker Publish

on:
  push:
    branches:
      - main  # Adjust this if you want to push on a different branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write  # Allows pushing to GitHub Container Registry
      # `packages: write` permission is required to publish Docker images to GHCR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/dhiegosilva/pricecollector/price-collector:latest
            ghcr.io/dhiegosilva/pricecollector/price-collector:${{ github.sha }}

      - name: Log out of GitHub Container Registry
        run: docker logout ghcr.io
