name: Build and Publish Docker Image

on:
  push:
    branches:
      - master
    tags:
      - 'v*'  # Only trigger on tags that start with "v", e.g., v1.0, v2.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine Docker Tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/heads/master ]]; then
            echo "tag=latest" >> $GITHUB_ENV
          else
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "tag=${TAG_NAME}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/price-collector:${{ env.tag }} .

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.repository }}/price-collector:${{ env.tag }}
